language: erlang

env:
  global:
    - LUAROCKS_VER=2.1.0
    - LUAROCKS_BASE=luarocks-$LUAROCKS_VER
    - LUAROCKS_INSTALL=wget
    - LUAROCKS_GITTAG=master
    # - LUAROCKS_GITTAG=v$LUAROCKS_VER
  matrix:
    - LUA=lua5.1 LUA_DEV=liblua5.1-dev LUA_VER=5.1 LUA_SFX=5.1 LUA_INCDIR=/usr/include/lua5.1
    - LUA=lua5.2 LUA_DEV=liblua5.2-dev LUA_VER=5.2 LUA_SFX=5.2 LUA_INCDIR=/usr/include/lua5.2
    - LUA=luajit LUA_DEV=libluajit-5.1-dev LUA_VER=5.1 LUA_SFX=jit LUA_INCDIR=/usr/include/luajit-2.0

branches:
  only:
    - master

before_install:
  - if [ $LUA = "luajit" ]; then
      sudo add-apt-repository ppa:mwild1/ppa -y && sudo apt-get update -y;
    fi
  - sudo apt-get install $LUA
  - sudo apt-get install $LUA_DEV
  - lua$LUA_SFX -v
  # Install a recent luarocks release
  - if [ $LUAROCKS_INSTALL = "git" ]; then
      git clone https://github.com/keplerproject/luarocks.git;
      cd luarocks;
      git checkout $LUAROCKS_GITTAG;
    else
      wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz;
      tar zxvpf $LUAROCKS_BASE.tar.gz;
      cd $LUAROCKS_BASE;
    fi
  - ./configure --lua-version=$LUA_VER --lua-suffix=$LUA_SFX --with-lua-include="$LUA_INCDIR"
  - sudo make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

install:
  - sudo apt-get install libzmq3
  - if [ $LUA = "luajit" ]; then
      sudo luarocks install https://raw.github.com/moteus/lzmq/master/rockspecs/lzmq-ffi-scm-0.rockspec;
    else
      sudo apt-get install libzmq3-dev;
      sudo luarocks install https://raw.github.com/moteus/lzmq/master/rockspecs/lzmq-scm-0.rockspec;
    fi
  - sudo luarocks install lunitx
  - sudo luarocks make rockspecs/lzmq-pool-scm-0.rockspec

script:
  - cd test
  - lunit.sh -i lua$LUA_SFX test_pool.lua

notifications:
  email:
    on_success: change
    on_failure: always